package com.harnessagent.marketdata;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Instant;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import org.springframework.stereotype.Component;

@Component
public class MockMarketDataProvider implements MarketDataProvider {

    private static final String DISCLAIMER =
            "Mock market data is for local development and educational demonstration only. It is not real-time market data and must not be used for investment decisions.";

    private final MarketDataProperties properties;
    private final Map<String, BigDecimal> seededPrices = Map.of(
            "AAPL", new BigDecimal("189.320000"),
            "MSFT", new BigDecimal("421.450000"),
            "VOO", new BigDecimal("508.770000"),
            "SPY", new BigDecimal("548.160000"),
            "QQQ", new BigDecimal("475.250000"),
            "000001", new BigDecimal("10.880000")
    );

    public MockMarketDataProvider(MarketDataProperties properties) {
        this.properties = properties;
    }

    @Override
    public MarketDataProviderDescriptor descriptor() {
        return new MarketDataProviderDescriptor(
                properties.mockProviderName(),
                MarketDataSourceType.MOCK,
                properties.mockEnabled(),
                false,
                "Deterministic local mock quotes for development, demos, and tests."
        );
    }

    @Override
    public Optional<MarketQuote> fetchQuote(MarketDataRequest request) {
        if (!properties.mockEnabled()) {
            return Optional.empty();
        }

        String symbol = normalize(request.symbol(), "UNKNOWN").toUpperCase(Locale.ROOT);
        String exchange = normalize(request.exchange(), "GLOBAL").toUpperCase(Locale.ROOT);
        String currency = normalize(request.currency(), "USD").toUpperCase(Locale.ROOT);
        BigDecimal latestPrice = seededPrices.getOrDefault(symbol, generatedPrice(symbol));
        BigDecimal previousClose = latestPrice.multiply(new BigDecimal("0.985000")).setScale(6, RoundingMode.HALF_UP);
        BigDecimal changeAmount = latestPrice.subtract(previousClose).setScale(6, RoundingMode.HALF_UP);
        BigDecimal changePercent = previousClose.compareTo(BigDecimal.ZERO) == 0
                ? BigDecimal.ZERO
                : changeAmount.divide(previousClose, 6, RoundingMode.HALF_UP);

        return Optional.of(new MarketQuote(
                symbol,
                exchange,
                currency,
                latestPrice,
                previousClose,
                changeAmount,
                changePercent,
                Instant.now(),
                descriptor().name(),
                descriptor().sourceType(),
                new BigDecimal("0.350000"),
                java.util.List.of(
                        "Quote is generated by a deterministic local mock provider.",
                        "Price is intended to exercise portfolio valuation flow before external market data integration."
                ),
                java.util.List.of(
                        "Mock prices are not real-time quotes.",
                        "Do not use mock data for actual investment decisions."
                ),
                DISCLAIMER
        ));
    }

    private BigDecimal generatedPrice(String symbol) {
        int bucket = Math.abs(symbol.hashCode() % 9000) + 1000;
        return new BigDecimal(bucket).divide(new BigDecimal("37"), 6, RoundingMode.HALF_UP);
    }

    private String normalize(String value, String fallback) {
        if (value == null || value.isBlank()) {
            return fallback;
        }
        return value.trim();
    }
}
