package com.harnessagent.agent;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.harnessagent.marketdata.MarketDataSourceType;
import com.harnessagent.marketdata.MarketQuote;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import org.junit.jupiter.api.Test;

class InvestmentAnalysisServiceTest {

    private final InvestmentAnalysisService service = new InvestmentAnalysisService(
            null,
            null,
            List.of(),
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            new ObjectMapper()
    );

    @Test
    void repairsObjectInvestmentSummaryWithoutLeakingRawJson() {
        String rawContent = """
                {
                  "investmentSummary": {
                    "assetName": ["AAPL", "NASDAQ"],
                    "currency": "USD",
                    "latestPrice": 189.32,
                    "previousClose": 186.48,
                    "changePercent": 0.015228
                  },
                  "keyObservations": ["AAPL moved while NASDAQ is the exchange."],
                  "assumptions": ["Mock quote only."],
                  "riskWarnings": ["Not investment advice."],
                  "educationalNotes": ["Use real market data for production decisions."],
                  "confidence": 0.35
                }
                """;

        InvestmentAnalysisContent content = service.parseContent(rawContent, quote());

        assertThat(content.investmentSummary())
                .contains("Analysis for AAPL on NASDAQ in USD")
                .doesNotContain("\"investmentSummary\"")
                .doesNotContain("assetName");
        assertThat(content.keyObservations()).containsExactly("AAPL moved while NASDAQ is the exchange.");
        assertThat(content.confidence()).isEqualByComparingTo("0.35");
    }

    @Test
    void fallbackDoesNotExposeInvalidRawModelOutput() {
        InvestmentAnalysisContent content = service.parseContent("```json\n{ \"investmentSummary\": ", quote());

        assertThat(content.investmentSummary())
                .contains("valid structured analysis")
                .doesNotContain("investmentSummary");
        assertThat(content.assumptions())
                .containsExactly("The response parser could not validate strict JSON from the model output.");
        assertThat(content.confidence()).isEqualByComparingTo("0.25");
    }

    private MarketQuote quote() {
        return new MarketQuote(
                "AAPL",
                "NASDAQ",
                "USD",
                new BigDecimal("189.320000"),
                new BigDecimal("186.480000"),
                new BigDecimal("2.840000"),
                new BigDecimal("0.015228"),
                Instant.parse("2026-07-06T00:00:00Z"),
                "local-mock",
                MarketDataSourceType.MOCK,
                new BigDecimal("0.350000"),
                List.of("Quote is generated by a deterministic local mock provider."),
                List.of("Mock prices are not real-time quotes."),
                "Mock market data is for local development and educational demonstration only."
        );
    }
}
